# Generated by Django 5.2.1 on 2025-05-14 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_venta_itemventa'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemVenta',
            new_name='DetalleVenta',
        ),
        migrations.RenameField(
            model_name='detalleventa',
            old_name='precio_unitario',
            new_name='precioTotal',
        ),
        migrations.RenameField(
            model_name='detalleventa',
            old_name='tipodeenvio',
            new_name='tipoenvio',
        ),
    ]
