# Generated by Django 5.2.1 on 2025-05-28 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleventa',
            name='estadopedido',
        ),
        migrations.AddField(
            model_name='venta',
            name='estadopedido',
            field=models.IntegerField(default=0),
        ),
    ]
