# Generated by Django 5.2.1 on 2025-05-28 01:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_detalleventa_estadopedido_venta_estadopedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='id_cliente',
        ),
        migrations.AddField(
            model_name='venta',
            name='cliente',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
