# Generated by Django 5.2.1 on 2025-05-28 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_venta_id_cliente_venta_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='estadopedido',
            field=models.IntegerField(choices=[(0, 'REcivido'), (1, 'Aprobado'), (2, 'Enviado'), (2, 'Rechazado')], default=0),
        ),
    ]
