# Generated by Django 5.2.1 on 2025-05-28 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_venta_estadopedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='estadopedido',
            field=models.IntegerField(choices=[(0, 'Recivido'), (1, 'Aprobado'), (2, 'Enviado'), (3, 'Rechazado'), (4, 'Preparando')], default=0),
        ),
    ]
