# Generated by Django 5.2.3 on 2025-06-21 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_venta_estadopedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='paypal_transaction_id',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
